# Benchmark tool for SLEEF math library

link_directories(${sleef_BINARY_DIR}/lib)
if(CMAKE_INSTALL_PREFIX)
  link_directories(${CMAKE_INSTALL_PREFIX}/lib64)
  link_directories(${CMAKE_INSTALL_PREFIX}/lib)
endif()
include_directories(${sleef_BINARY_DIR}/include)

set(CMAKE_C_FLAGS "${ORG_CMAKE_C_FLAGS} ${SLEEF_C_FLAGS}")

# Scalar benchmark
add_executable(benchmark benchmark.c)
target_link_libraries(benchmark ${TARGET_LIBSLEEF} ${LIBM})
if(TLFLOAT_LIBRARIES)
  target_link_libraries(benchmark ${TLFLOAT_LIBRARIES})
endif()
target_compile_definitions(benchmark PRIVATE ${COMMON_TARGET_DEFINITIONS})
set_target_properties(benchmark PROPERTIES C_STANDARD 99)
add_dependencies(benchmark ${TARGET_HEADERS})

# SIMD benchmark (if applicable architectures are available)
if(COMPILER_SUPPORTS_SSE2 AND SLEEF_ARCH_X86)
  add_executable(benchmark_sse2 benchmark_simd.c)
  target_compile_options(benchmark_sse2 PRIVATE ${FLAGS_ENABLE_SSE2})
  target_compile_definitions(benchmark_sse2 PRIVATE ENABLE_SSE2=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_sse2 ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_sse2 PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_sse2 ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_AVX2 AND SLEEF_ARCH_X86)
  add_executable(benchmark_avx2 benchmark_simd.c)
  target_compile_options(benchmark_avx2 PRIVATE ${FLAGS_ENABLE_AVX2})
  target_compile_definitions(benchmark_avx2 PRIVATE ENABLE_AVX2=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_avx2 ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_avx2 PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_avx2 ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_AVX512F AND SLEEF_ARCH_X86)
  add_executable(benchmark_avx512f benchmark_simd.c)
  target_compile_options(benchmark_avx512f PRIVATE ${FLAGS_ENABLE_AVX512F})
  target_compile_definitions(benchmark_avx512f PRIVATE ENABLE_AVX512F=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_avx512f ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_avx512f PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_avx512f ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_ADVSIMD AND SLEEF_ARCH_AARCH64)
  add_executable(benchmark_advsimd benchmark_simd.c)
  target_compile_options(benchmark_advsimd PRIVATE ${FLAGS_ENABLE_ADVSIMD})
  target_compile_definitions(benchmark_advsimd PRIVATE ENABLE_ADVSIMD=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_advsimd ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_advsimd PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_advsimd ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_SVE AND SLEEF_ARCH_AARCH64)
  add_executable(benchmark_sve benchmark_simd.c)
  target_compile_options(benchmark_sve PRIVATE ${FLAGS_ENABLE_SVE})
  target_compile_definitions(benchmark_sve PRIVATE ENABLE_SVE=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_sve ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_sve PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_sve ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_RVVM1)
  add_executable(benchmark_rvvm1 benchmark_simd.c)
  target_compile_options(benchmark_rvvm1 PRIVATE ${FLAGS_ENABLE_RVVM1})
  target_compile_definitions(benchmark_rvvm1 PRIVATE ENABLE_RVVM1=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_rvvm1 ${TARGET_LIBSLEEF} ${LIBM})
  if(TLFLOAT_LIBRARIES)
    target_link_libraries(benchmark_rvvm1 ${TLFLOAT_LIBRARIES})
  endif()
  set_target_properties(benchmark_rvvm1 PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_rvvm1 ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_RVVM2)
  add_executable(benchmark_rvvm2 benchmark_simd.c)
  target_compile_options(benchmark_rvvm2 PRIVATE ${FLAGS_ENABLE_RVVM2})
  target_compile_definitions(benchmark_rvvm2 PRIVATE ENABLE_RVVM2=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_rvvm2 ${TARGET_LIBSLEEF} ${LIBM})
  if(TLFLOAT_LIBRARIES)
    target_link_libraries(benchmark_rvvm2 ${TLFLOAT_LIBRARIES})
  endif()
  set_target_properties(benchmark_rvvm2 PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_rvvm2 ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_VSX AND SLEEF_ARCH_PPC64)
  add_executable(benchmark_vsx benchmark_simd.c)
  target_compile_options(benchmark_vsx PRIVATE ${FLAGS_ENABLE_VSX})
  target_compile_definitions(benchmark_vsx PRIVATE ENABLE_VSX=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_vsx ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_vsx PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_vsx ${TARGET_HEADERS})
endif()

if(COMPILER_SUPPORTS_VXE AND SLEEF_ARCH_S390X)
  add_executable(benchmark_vxe benchmark_simd.c)
  target_compile_options(benchmark_vxe PRIVATE ${FLAGS_ENABLE_VXE})
  target_compile_definitions(benchmark_vxe PRIVATE ENABLE_VXE=1 ${COMMON_TARGET_DEFINITIONS})
  target_link_libraries(benchmark_vxe ${TARGET_LIBSLEEF} ${LIBM})
  set_target_properties(benchmark_vxe PROPERTIES C_STANDARD 99)
  add_dependencies(benchmark_vxe ${TARGET_HEADERS})
endif()

